/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicResourcesRouteImport } from './routes/_public/resources'
import { Route as PublicQuizRouteImport } from './routes/_public/quiz'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicPetsIdRouteImport } from './routes/_public/pets.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResourcesRoute = PublicResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => PublicRoute,
} as any)
const PublicQuizRoute = PublicQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPetsIdRoute = PublicPetsIdRouteImport.update({
  id: '/pets/$id',
  path: '/pets/$id',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/quiz': typeof PublicQuizRoute
  '/resources': typeof PublicResourcesRoute
  '/search': typeof PublicSearchRoute
  '/pets/$id': typeof PublicPetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/quiz': typeof PublicQuizRoute
  '/resources': typeof PublicResourcesRoute
  '/search': typeof PublicSearchRoute
  '/': typeof PublicIndexRoute
  '/pets/$id': typeof PublicPetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/quiz': typeof PublicQuizRoute
  '/_public/resources': typeof PublicResourcesRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/pets/$id': typeof PublicPetsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/quiz'
    | '/resources'
    | '/search'
    | '/pets/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/quiz'
    | '/resources'
    | '/search'
    | '/'
    | '/pets/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_public'
    | '/_public/about'
    | '/_public/quiz'
    | '/_public/resources'
    | '/_public/search'
    | '/_public/'
    | '/_public/pets/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/resources': {
      id: '/_public/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof PublicResourcesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/quiz': {
      id: '/_public/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof PublicQuizRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/pets/$id': {
      id: '/_public/pets/$id'
      path: '/pets/$id'
      fullPath: '/pets/$id'
      preLoaderRoute: typeof PublicPetsIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicQuizRoute: typeof PublicQuizRoute
  PublicResourcesRoute: typeof PublicResourcesRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicPetsIdRoute: typeof PublicPetsIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicQuizRoute: PublicQuizRoute,
  PublicResourcesRoute: PublicResourcesRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicPetsIdRoute: PublicPetsIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
