import type { Pet } from '@repo/domain'

export const adminPets: Pet[] = [
  {
    id: '4092',
    name: 'Barnaby',
    type: 'dog',
    breed: 'Beagle Mix',
    age: 'adult',
    ageLabel: '4 yrs',
    gender: 'male',
    size: 'medium',
    location: { city: 'Seattle', state: 'WA' },
    photos: [
      'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=600&q=80',
    ],
    description: 'Beagle mix recovering at Downtown Rescue.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'downtown-rescue',
    status: 'medical',
    createdAt: '2026-04-02',
  },
  {
    id: '4105',
    name: 'Marmalade',
    type: 'cat',
    breed: 'Domestic Shorthair',
    age: 'young',
    ageLabel: '2 yrs',
    gender: 'female',
    size: 'small',
    location: { city: 'Tacoma', state: 'WA' },
    photos: [
      'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=600&q=80',
    ],
    description: 'Affectionate shorthair looking for a quiet home.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'westside-haven',
    status: 'available',
    createdAt: '2026-04-15',
  },
  {
    id: '3988',
    name: 'Cooper',
    type: 'dog',
    breed: 'Golden Retriever',
    age: 'puppy',
    ageLabel: '5 mos',
    gender: 'male',
    size: 'medium',
    location: { city: 'Seattle', state: 'WA' },
    photos: [
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&q=80',
    ],
    description: 'Energetic puppy already placed with a forever family.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'downtown-rescue',
    status: 'adopted',
    createdAt: '2026-03-21',
  },
  {
    id: '4112',
    name: 'Luna',
    type: 'cat',
    breed: 'Persian Mix',
    age: 'young',
    ageLabel: '1 yr',
    gender: 'female',
    size: 'small',
    location: { city: 'Portland', state: 'OR' },
    photos: [
      'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&q=80',
    ],
    description: 'Calm Persian mix, perfect lap companion.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'northside-clinic',
    status: 'available',
    createdAt: '2026-04-22',
  },
  {
    id: '4117',
    name: 'Pepper',
    type: 'dog',
    breed: 'Border Collie',
    age: 'young',
    ageLabel: '3 yrs',
    gender: 'female',
    size: 'medium',
    location: { city: 'Portland', state: 'OR' },
    photos: [
      'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=600&q=80',
    ],
    description: 'Smart Border Collie, needs an active home.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'sunny-pines',
    status: 'available',
    createdAt: '2026-04-30',
  },
  {
    id: '4120',
    name: 'Mochi',
    type: 'dog',
    breed: 'Shiba Inu',
    age: 'young',
    ageLabel: '2 yrs',
    gender: 'male',
    size: 'small',
    location: { city: 'Seattle', state: 'WA' },
    photos: [
      'https://images.unsplash.com/photo-1568572933382-74d440642117?w=600&q=80',
    ],
    description: 'Spirited Shiba Inu, loves long walks.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'urban-tails',
    status: 'available',
    createdAt: '2026-05-04',
  },
  {
    id: '4124',
    name: 'Theo',
    type: 'cat',
    breed: 'Tabby',
    age: 'puppy',
    ageLabel: '6 mos',
    gender: 'male',
    size: 'small',
    location: { city: 'Tacoma', state: 'WA' },
    photos: [
      'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&q=80',
    ],
    description: 'Young tabby in foster care while finishing treatment.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'lakeside',
    status: 'medical',
    createdAt: '2026-05-08',
  },
  {
    id: '4130',
    name: 'Daisy',
    type: 'dog',
    breed: 'Labrador Mix',
    age: 'senior',
    ageLabel: '7 yrs',
    gender: 'female',
    size: 'large',
    location: { city: 'Boise', state: 'ID' },
    photos: [
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80',
    ],
    description: 'Gentle senior Lab, recently adopted into her forever home.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'happy-paws',
    status: 'adopted',
    createdAt: '2026-02-19',
  },
]
