import type { Pet } from '@repo/domain'

export const pets: Pet[] = [
  {
    id: 'bella',
    name: 'Bella',
    type: 'dog',
    breed: 'Golden Retriever Mix',
    age: 'young',
    ageLabel: '2 yrs',
    gender: 'female',
    size: 'large',
    location: { city: 'Seattle', state: 'WA', zip: '98101', distanceMiles: 12 },
    photos: ['/pet-images/bella.jpg'],
    description: 'Sweet and gentle Golden Retriever mix who loves long walks.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-1',
    status: 'available',
    createdAt: '2026-04-12',
  },
  {
    id: 'oliver',
    name: 'Oliver',
    type: 'cat',
    breed: 'Domestic Shorthair',
    age: 'puppy',
    ageLabel: '8 mos',
    gender: 'male',
    size: 'small',
    location: { city: 'Portland', state: 'OR', zip: '97201', distanceMiles: 22 },
    photos: ['/pet-images/oliver.jpg'],
    description: 'Curious and playful kitten ready for a forever home.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-2',
    status: 'available',
    createdAt: '2026-05-01',
  },
  {
    id: 'max',
    name: 'Max',
    type: 'dog',
    breed: 'German Shepherd',
    age: 'adult',
    ageLabel: '4 yrs',
    gender: 'male',
    size: 'large',
    location: { city: 'Austin', state: 'TX', zip: '73301', distanceMiles: 35 },
    photos: [],
    description: 'Loyal and protective shepherd looking for an active family.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-3',
    status: 'available',
    createdAt: '2026-03-20',
  },
  {
    id: 'luna',
    name: 'Luna',
    type: 'cat',
    breed: 'Siamese Mix',
    age: 'young',
    ageLabel: '1.5 yrs',
    gender: 'female',
    size: 'small',
    location: { city: 'Denver', state: 'CO', zip: '80014', distanceMiles: 18 },
    photos: [],
    description: 'Quiet and affectionate Siamese mix.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-4',
    status: 'available',
    createdAt: '2026-04-28',
  },
  {
    id: 'nala',
    name: 'Nala',
    type: 'dog',
    breed: 'Shepherd & Black Labrador Retriever Mix',
    age: 'adult',
    ageLabel: '3 yrs',
    gender: 'female',
    size: 'large',
    location: { city: 'Bronx', state: 'NY', zip: '10461', distanceMiles: 1 },
    photos: ['/pet-images/nala.jpg'],
    description: 'Gentle giant who adores cuddles after a long walk.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-5',
    status: 'available',
    createdAt: '2026-05-15',
  },
  {
    id: 'chester',
    name: 'Chester',
    type: 'dog',
    breed: 'American Staffordshire Terrier',
    age: 'adult',
    ageLabel: '5 yrs',
    gender: 'male',
    size: 'large',
    location: { city: 'Bronx', state: 'NY', zip: '10461', distanceMiles: 1 },
    photos: ['/pet-images/chester.jpg'],
    description: 'Big-hearted boy with a goofy grin.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-5',
    status: 'available',
    createdAt: '2026-05-10',
  },
  {
    id: 'hershey',
    name: 'Hershey',
    type: 'dog',
    breed: 'Pit Bull Terrier & Bulldog',
    age: 'adult',
    ageLabel: '4 yrs',
    gender: 'female',
    size: 'large',
    location: { city: 'Bronx', state: 'NY', zip: '10461', distanceMiles: 1 },
    photos: ['/pet-images/hershey.jpg'],
    description: 'Sweet, snuggly girl who loves naps on the couch.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-6',
    status: 'available',
    createdAt: '2026-05-12',
  },
  {
    id: 'daisy-sue',
    name: 'Daisy Sue',
    type: 'dog',
    breed: 'Pointer & Australian Cattle Dog / Blue Heeler',
    age: 'young',
    ageLabel: '1 yr',
    gender: 'female',
    size: 'medium',
    location: { city: 'Bronx', state: 'NY', zip: '10461', distanceMiles: 1 },
    photos: ['/pet-images/daisy-sue.jpg'],
    description: 'Energetic explorer who would love a yard to run in.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-7',
    status: 'available',
    createdAt: '2026-05-18',
  },
  {
    id: 'tessa',
    name: 'Tessa',
    type: 'dog',
    breed: 'Australian Shepherd',
    age: 'adult',
    ageLabel: '3 yrs',
    gender: 'female',
    size: 'medium',
    location: { city: 'Albany', state: 'NY', zip: '12207', distanceMiles: 145 },
    photos: ['/pet-images/tessa.jpg'],
    description: 'Smart, bonded Aussie who knows several tricks.',
    outOfTown: true,
    transportAvailable: true,
    shelterId: 'shelter-8',
    status: 'available',
    createdAt: '2026-04-30',
  },
  {
    id: 'navajo',
    name: 'Navajo (Nav)',
    type: 'dog',
    breed: 'Pit Bull Terrier',
    age: 'adult',
    ageLabel: '4 yrs',
    gender: 'male',
    size: 'large',
    location: { city: 'Bronx', state: 'NY', zip: '10461', distanceMiles: 1 },
    photos: ['/pet-images/navajo.jpg'],
    description: 'Happy, mouthy boy who loves squeaky toys.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-5',
    status: 'available',
    createdAt: '2026-05-14',
  },
  {
    id: 'rocky',
    name: 'Rocky',
    type: 'dog',
    breed: 'Boxer',
    age: 'adult',
    ageLabel: '5 yrs',
    gender: 'male',
    size: 'large',
    location: { city: 'Brooklyn', state: 'NY', zip: '11201', distanceMiles: 8 },
    photos: [],
    description: 'A goofy boxer with endless energy.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-9',
    status: 'available',
    createdAt: '2026-04-22',
  },
  {
    id: 'milo',
    name: 'Milo',
    type: 'dog',
    breed: 'Beagle',
    age: 'puppy',
    ageLabel: '6 mos',
    gender: 'male',
    size: 'small',
    location: { city: 'Queens', state: 'NY', zip: '11377', distanceMiles: 6 },
    photos: [],
    description: 'A curious beagle pup who loves to sniff.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-10',
    status: 'available',
    createdAt: '2026-05-05',
  },
  {
    id: 'whiskers',
    name: 'Whiskers',
    type: 'cat',
    breed: 'Maine Coon',
    age: 'adult',
    ageLabel: '6 yrs',
    gender: 'male',
    size: 'large',
    location: { city: 'Manhattan', state: 'NY', zip: '10001', distanceMiles: 9 },
    photos: [],
    description: 'A gentle giant cat who loves quiet afternoons.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-11',
    status: 'available',
    createdAt: '2026-03-12',
  },
  {
    id: 'mittens',
    name: 'Mittens',
    type: 'cat',
    breed: 'Tabby',
    age: 'senior',
    ageLabel: '11 yrs',
    gender: 'female',
    size: 'small',
    location: { city: 'Queens', state: 'NY', zip: '11377', distanceMiles: 6 },
    photos: [],
    description: 'A sweet senior who would love a quiet home.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-12',
    status: 'available',
    createdAt: '2026-02-18',
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    type: 'cat',
    breed: 'Domestic Shorthair',
    age: 'young',
    ageLabel: '2 yrs',
    gender: 'female',
    size: 'small',
    location: { city: 'Bronx', state: 'NY', zip: '10461', distanceMiles: 2 },
    photos: [],
    description: 'A playful tortie with strong opinions on dinner.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-13',
    status: 'available',
    createdAt: '2026-05-02',
  },
  {
    id: 'shadow',
    name: 'Shadow',
    type: 'cat',
    breed: 'Domestic Shorthair',
    age: 'adult',
    ageLabel: '4 yrs',
    gender: 'male',
    size: 'medium',
    location: { city: 'Brooklyn', state: 'NY', zip: '11201', distanceMiles: 8 },
    photos: [],
    description: 'A sleek black cat who follows you around the house.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-9',
    status: 'available',
    createdAt: '2026-04-15',
  },
  {
    id: 'biscuit',
    name: 'Biscuit',
    type: 'other',
    breed: 'Rabbit',
    age: 'young',
    ageLabel: '1 yr',
    gender: 'male',
    size: 'small',
    location: { city: 'Bronx', state: 'NY', zip: '10461', distanceMiles: 3 },
    photos: [],
    description: 'A fluffy lop-eared rabbit looking for a quiet home.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-13',
    status: 'available',
    createdAt: '2026-04-10',
  },
  {
    id: 'nibbles',
    name: 'Nibbles',
    type: 'other',
    breed: 'Guinea Pig',
    age: 'young',
    ageLabel: '8 mos',
    gender: 'female',
    size: 'small',
    location: { city: 'Queens', state: 'NY', zip: '11377', distanceMiles: 7 },
    photos: [],
    description: 'A chatty guinea pig who loves veggies.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-12',
    status: 'available',
    createdAt: '2026-04-25',
  },
  {
    id: 'cooper',
    name: 'Cooper',
    type: 'dog',
    breed: 'Labrador Retriever',
    age: 'adult',
    ageLabel: '3 yrs',
    gender: 'male',
    size: 'large',
    location: { city: 'Yonkers', state: 'NY', zip: '10701', distanceMiles: 14 },
    photos: [],
    description: 'A classic chocolate lab who fetches anything.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-14',
    status: 'available',
    createdAt: '2026-04-02',
  },
  {
    id: 'sadie',
    name: 'Sadie',
    type: 'dog',
    breed: 'Border Collie',
    age: 'adult',
    ageLabel: '4 yrs',
    gender: 'female',
    size: 'medium',
    location: { city: 'Hartford', state: 'CT', zip: '06101', distanceMiles: 110 },
    photos: [],
    description: 'A whip-smart border collie who needs an active home.',
    outOfTown: true,
    transportAvailable: true,
    shelterId: 'shelter-15',
    status: 'available',
    createdAt: '2026-03-30',
  },
  {
    id: 'bruno',
    name: 'Bruno',
    type: 'dog',
    breed: 'Bulldog',
    age: 'senior',
    ageLabel: '9 yrs',
    gender: 'male',
    size: 'medium',
    location: { city: 'Bronx', state: 'NY', zip: '10461', distanceMiles: 2 },
    photos: [],
    description: 'A dignified senior bulldog seeking a comfy couch.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-5',
    status: 'available',
    createdAt: '2026-02-05',
  },
  {
    id: 'lily',
    name: 'Lily',
    type: 'dog',
    breed: 'Australian Cattle Dog / Blue Heeler',
    age: 'young',
    ageLabel: '1.5 yrs',
    gender: 'female',
    size: 'medium',
    location: { city: 'Newark', state: 'NJ', zip: '07101', distanceMiles: 18 },
    photos: [],
    description: 'A clever heeler who loves a good puzzle.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-16',
    status: 'available',
    createdAt: '2026-05-08',
  },
  {
    id: 'simba',
    name: 'Simba',
    type: 'cat',
    breed: 'Persian',
    age: 'adult',
    ageLabel: '5 yrs',
    gender: 'male',
    size: 'medium',
    location: { city: 'Manhattan', state: 'NY', zip: '10001', distanceMiles: 9 },
    photos: [],
    description: 'A regal Persian with a luxurious coat.',
    outOfTown: false,
    transportAvailable: false,
    shelterId: 'shelter-11',
    status: 'available',
    createdAt: '2026-03-25',
  },
  {
    id: 'penny',
    name: 'Penny',
    type: 'dog',
    breed: 'Australian Shepherd',
    age: 'puppy',
    ageLabel: '4 mos',
    gender: 'female',
    size: 'medium',
    location: { city: 'Stamford', state: 'CT', zip: '06901', distanceMiles: 38 },
    photos: [],
    description: 'A bouncy aussie pup ready to learn.',
    outOfTown: true,
    transportAvailable: true,
    shelterId: 'shelter-17',
    status: 'available',
    createdAt: '2026-05-19',
  },
]
