import type { Shelter } from '@repo/domain'

export const shelters: Shelter[] = [
  {
    id: 'sunny-pines',
    name: 'Sunny Pines Rescue',
    district: 'North District',
    contact: 'Sarah Jenkins',
    status: 'active',
    pets: 45,
    lastActivity: '2 hours ago',
    location: 'Portland, OR',
    appliedAt: 'Oct 12, 2023',
  },
  {
    id: 'urban-tails',
    name: 'Urban Tails Haven',
    district: 'Downtown Metro',
    contact: 'Marcus Chen',
    status: 'pending',
    pets: 12,
    lastActivity: '1 day ago',
    location: 'Seattle, WA',
    appliedAt: 'Oct 14, 2023',
  },
  {
    id: 'happy-paws',
    name: 'Happy Paws Sanctuary',
    district: 'East District',
    contact: 'Elena Rodriguez',
    status: 'active',
    pets: 118,
    lastActivity: 'Just now',
    location: 'Boise, ID',
    appliedAt: 'Sep 02, 2023',
  },
  {
    id: 'valley-hope',
    name: 'Valley Hope Animal Care',
    district: 'South District',
    contact: 'David Kim',
    status: 'suspended',
    pets: 0,
    lastActivity: '2 weeks ago',
    location: 'Salem, OR',
    appliedAt: 'Aug 18, 2023',
  },
  {
    id: 'lakeside',
    name: 'Lakeside Felines',
    district: 'West District',
    contact: 'Amanda Foster',
    status: 'active',
    pets: 32,
    lastActivity: '5 hours ago',
    location: 'Tacoma, WA',
    appliedAt: 'Jul 11, 2023',
  },
  {
    id: 'safe-haven',
    name: 'Safe Haven Rescue',
    district: 'North District',
    contact: 'Jordan Lee',
    status: 'pending',
    pets: 8,
    lastActivity: '3 days ago',
    location: 'Portland, OR',
    appliedAt: 'Oct 12, 2023',
  },
  {
    id: 'sunny-days',
    name: 'Sunny Days Sanctuary',
    district: 'Central',
    contact: 'Priya Sharma',
    status: 'pending',
    pets: 14,
    lastActivity: '6 days ago',
    location: 'Austin, TX',
    appliedAt: 'Oct 14, 2023',
  },
  {
    id: 'paws-claws',
    name: 'Paws & Claws Network',
    district: 'Midwest',
    contact: 'Riley Park',
    status: 'pending',
    pets: 22,
    lastActivity: '1 week ago',
    location: 'Chicago, IL',
    appliedAt: 'Oct 15, 2023',
  },
  {
    id: 'downtown-rescue',
    name: 'Downtown Rescue',
    district: 'Downtown Metro',
    contact: 'Casey Brooks',
    status: 'active',
    pets: 28,
    lastActivity: '4 hours ago',
    location: 'Seattle, WA',
    appliedAt: 'Jun 02, 2023',
  },
  {
    id: 'westside-haven',
    name: 'Westside Haven',
    district: 'West District',
    contact: 'Morgan Liu',
    status: 'active',
    pets: 19,
    lastActivity: '1 hour ago',
    location: 'Tacoma, WA',
    appliedAt: 'May 14, 2023',
  },
  {
    id: 'northside-clinic',
    name: 'Northside Clinic',
    district: 'North District',
    contact: 'Dr. Avery Patel',
    status: 'active',
    pets: 7,
    lastActivity: '12 hours ago',
    location: 'Portland, OR',
    appliedAt: 'Apr 09, 2023',
  },
]

export function getShelter(id: string): Shelter | undefined {
  return shelters.find((s) => s.id === id)
}
