/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminPetsRouteImport } from './routes/_admin.pets'
import { Route as AdminSheltersIndexRouteImport } from './routes/_admin.shelters.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminSheltersIdStatusRouteImport } from './routes/_admin.shelters.$id.status'
import { Route as AdminSheltersIdReviewRouteImport } from './routes/_admin.shelters.$id.review'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPetsRoute = AdminPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSheltersIndexRoute = AdminSheltersIndexRouteImport.update({
  id: '/shelters/',
  path: '/shelters/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSheltersIdStatusRoute = AdminSheltersIdStatusRouteImport.update({
  id: '/shelters/$id/status',
  path: '/shelters/$id/status',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSheltersIdReviewRoute = AdminSheltersIdReviewRouteImport.update({
  id: '/shelters/$id/review',
  path: '/shelters/$id/review',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/pets': typeof AdminPetsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/shelters/': typeof AdminSheltersIndexRoute
  '/shelters/$id/review': typeof AdminSheltersIdReviewRoute
  '/shelters/$id/status': typeof AdminSheltersIdStatusRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/pets': typeof AdminPetsRoute
  '/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/shelters': typeof AdminSheltersIndexRoute
  '/shelters/$id/review': typeof AdminSheltersIdReviewRoute
  '/shelters/$id/status': typeof AdminSheltersIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/pets': typeof AdminPetsRoute
  '/_admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_admin/shelters/': typeof AdminSheltersIndexRoute
  '/_admin/shelters/$id/review': typeof AdminSheltersIdReviewRoute
  '/_admin/shelters/$id/status': typeof AdminSheltersIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pets'
    | '/api/auth/$'
    | '/shelters/'
    | '/shelters/$id/review'
    | '/shelters/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/pets'
    | '/'
    | '/api/auth/$'
    | '/shelters'
    | '/shelters/$id/review'
    | '/shelters/$id/status'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/pets'
    | '/_admin/'
    | '/api/auth/$'
    | '/_admin/shelters/'
    | '/_admin/shelters/$id/review'
    | '/_admin/shelters/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pets': {
      id: '/_admin/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof AdminPetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shelters/': {
      id: '/_admin/shelters/'
      path: '/shelters'
      fullPath: '/shelters/'
      preLoaderRoute: typeof AdminSheltersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/shelters/$id/status': {
      id: '/_admin/shelters/$id/status'
      path: '/shelters/$id/status'
      fullPath: '/shelters/$id/status'
      preLoaderRoute: typeof AdminSheltersIdStatusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shelters/$id/review': {
      id: '/_admin/shelters/$id/review'
      path: '/shelters/$id/review'
      fullPath: '/shelters/$id/review'
      preLoaderRoute: typeof AdminSheltersIdReviewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPetsRoute: typeof AdminPetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSheltersIndexRoute: typeof AdminSheltersIndexRoute
  AdminSheltersIdReviewRoute: typeof AdminSheltersIdReviewRoute
  AdminSheltersIdStatusRoute: typeof AdminSheltersIdStatusRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPetsRoute: AdminPetsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSheltersIndexRoute: AdminSheltersIndexRoute,
  AdminSheltersIdReviewRoute: AdminSheltersIdReviewRoute,
  AdminSheltersIdStatusRoute: AdminSheltersIdStatusRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
